### ISSUE TITLE
`server` fails with runtime error when setting logging parameters via environmental variables

### ISSUE THREAD

**Issue by Rindrics** [m-mizutani/ghnotify#8]
relevant version: `v0.1.3`

## What occurs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x69d098]

goroutine 1 [running]:
github.com/urfave/cli/v2.(*GenericFlag).Apply(0x4000348340, 0xce0730?)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/flag_generic.go:77 +0xf8
github.com/urfave/cli/v2.flagSet({0xb4d266, 0x8}, {0x40005cd2c0, 0xb, 0x18?}, {{0x0?, 0x400014c2a0?}, 0x0?, 0x0?})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/flag.go:177 +0x150
github.com/urfave/cli/v2.(*Command).newFlagSet(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:281
github.com/urfave/cli/v2.(*Command).parseFlags(0x40003cb600, {0xce2638, 0x400014c2a0}, 0xa0?)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:314 +0x60
github.com/urfave/cli/v2.(*Command).Run(0x40003cb600, 0x4000548ac0, {0x4000030080, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:155 +0xa8
github.com/urfave/cli/v2.(*App).RunContext(0x4000028000, {0xce03b0?, 0x400003e020}, {0x4000030080, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x568
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
github.com/m-mizutani/ghnotify/pkg/controller/cmd.Run({0x4000030080, 0x4, 0x4})
	/src/pkg/controller/cmd/cli.go:204 +0xcb4
main.main()
	/src/main.go:10 +0x34
```

## When it occurs

part of my `docker-compose.yml`:
```
version: '3'
services:
  ghnotify:
    image: ghcr.io/m-mizutani/ghnotify:v0.1.3
    command:
      - --remote-url
      - http://opa_server:8181/v1/data/github/notify
      - serve
    env_file:
      - .env
    environment:
      - GHNOTIFY_ADDR=0.0.0.0:80
      - GHNOTIFY_WEBHOOK_SECRET=my-dummy-secret
      - GHNOTIFY_LOG_LEVEL=debug                    # set log-level from environmental variable
    ports:
      - 4080:80
    networks:
      - my_network
  opa_server
    ...
```

## Note

- The problem seems to be introduced by the following change: https://github.com/m-mizutani/ghnotify/commit/baf08365d80bf4e72b587ec87b11be26128874c6#diff-c476334f550b8032218c65595e89038bb8931089c22ceea3b27d45ce13d40e87L163-R186
- I already fixed the problem on https://github.com/m-mizutani/ghnotify/pull/7
